### ISSUE TITLE
数统学院-通识-数学模型

### ISSUE THREAD

**Issue by zyd8888102** [632team/Course-Selection-Guidance-in-CQU#1]
- 任课教师：肖剑
- 上课模式(传统/在线)：在线
- 总评：
个人非常推荐。老师上课幽默风趣，课堂内容充实也很有逻辑，可以学到确确实实的东西。
从matlab入门到一些简单的数学模型都讲的仔细，白痴可懂。
平时有三四次作业，都是巩固课讲上的内容，最后一次小论文。每次作业完都有四五个优秀作业展示，由同学上台展示。
上课一般是同学主动回答问题会加分，快结课会抽没有回答过的人回答问题。
最后评分=作业+课堂参与+期末论文（比重大）
关键是……给分高啊，只要平时作业认真一点，最后期末论文抱个大腿一起做，就可以轻松90左右~不会故意为难同学╮(╯_╰)╭被抽到了回答不来也没事，作业偶尔得B也没事。

- 评价列表：
  - 但是这门课比较抢手，特别是一些平时数模讲座的老师。如果网不好抢不到就算了。。平时老师会在数模课堂群里发关于数模的比赛的通知，非常认真负责。——二丹
---

**Comment by GooZy** [comment]
已添加:) 感谢点评。链接地址：[这里](https://github.com/632team/Course-Selection-Guidance-in-CQU/blob/master/%E5%85%A8%E6%A0%A1%E6%80%A7%E9%80%9A%E8%AF%86%E4%B8%8E%E7%B4%A0%E8%B4%A8%E8%AF%BE%E7%A8%8B/%E6%95%B0%E7%BB%9F%E5%AD%A6%E9%99%A2/%E6%95%B0%E5%AD%A6%E6%A8%A1%E5%9E%8B.md)
